NetCoreMvcClear/ViewModels/HomeViewModel.cs
using NetCoreMvcClear.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NetCoreMvcClear.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<RentItem> availableItems { get; set; }
    }
}

NetCoreMvcClear/ViewModels/RentCartViewModel.cs
using NetCoreMvcClear.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NetCoreMvcClear.ViewModels
{
    public class RentCartViewModel
    {
        public RentCart rentCart { get; set; }
    }
}

NetCoreMvcClear/ViewModels/RentItemViewModel.cs
using NetCoreMvcClear.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NetCoreMvcClear.ViewModels
{
    public class RentItemViewModel
    {
        public IEnumerable<RentItem> GetAllRentItems { get; set; }

        public string currentCategory { get; set; }
    }
}

NetCoreMvcClear/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using NetCoreMvcClear.Data.Interfaces;
using NetCoreMvcClear.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NetCoreMvcClear.Controllers
{
    public class HomeController : Controller
    {
        private readonly IRentItem _rentItem;

        public HomeController(IRentItem rentItem)
        {
            _rentItem = rentItem;
        }

        public ViewResult Index()
        {
            var homeItems = new HomeViewModel
            {
                availableItems = _rentItem.GetAvailableRentItems
            };

            return View(homeItems);
        }
    }
}

NetCoreMvcClear/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using NetCoreMvcClear.Data.Interfaces;
using NetCoreMvcClear.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NetCoreMvcClear.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrder _Order;
        private readonly RentCart _RentCart;

        public OrderController(IOrder order, RentCart rentCart)
        {
            this._Order = order;
            this._RentCart = rentCart;
        }

        public IActionResult Checkout()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            _RentCart.RentCartList = _RentCart.getRentItems();

            if(_RentCart.RentCartList.Count == 0)
            {
                ModelState.AddModelError("", "В корзине нет товаров");
            }

            if (ModelState.IsValid)
            {
                _Order.CreateOrder(order);
                return RedirectToAction("Complete");
            }

            return View(order);
        }

        public IActionResult Complete()
        {
            ViewBag.Message = "Заказ успешно обработан";
            return View();
        }
    }
}

NetCoreMvcClear/Controllers/RentCartController.cs
using Microsoft.AspNetCore.Mvc;
using NetCoreMvcClear.Data.Interfaces;
using NetCoreMvcClear.Data.Models;

using NetCoreMvcClear.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NetCoreMvcClear.Controllers
{
    public class RentCartController : Controller
    {
        private readonly IRentItem _rentItem;
        private readonly RentCart _rentCart;

        public RentCartController(IRentItem rentItem, RentCart rentCart)
        {
            _rentItem = rentItem;
            _rentCart = rentCart;
        }

        public ViewResult Index()
        {
            var items = _rentCart.getRentItems();
            _rentCart.RentCartList = items;

            var obj = new RentCartViewModel
            {
                rentCart = _rentCart
            };

            return View(obj);
        }

        public RedirectToActionResult addToCart(int id)
        {
            var item = _rentItem.AllRentItems.FirstOrDefault(i => i.Id == id);

            if(item != null)
            {
                _rentCart.AddToCart(item, 1);
            }
            return RedirectToAction("Index");
        }
    }
}

NetCoreMvcClear/Controllers/RentItemController.cs
using Microsoft.AspNetCore.Mvc;
using NetCoreMvcClear.Data.Interfaces;
using NetCoreMvcClear.Data.Models;
using NetCoreMvcClear.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NetCoreMvcClear.Controllers
{
    public class RentItemController : Controller
    {
        private readonly IRentItem _RentItems;
        private readonly ICategory _Categories;

        public RentItemController(IRentItem iRentItems, ICategory iCategories)
        {
            _RentItems = iRentItems;
            _Categories = iCategories;
        }

        [Route("RentItem/List")]
        [Route("RentItem/List/{category}")]
        public ViewResult List(string category)
        {
            string _category = category;
            IEnumerable<RentItem> rentItems;
            string currCategory = "";

            if (string.IsNullOrEmpty(category))
            {
                rentItems = _RentItems.AllRentItems.OrderBy(i => i.Id);
            }
            else
            {
                if(string.Equals("skyboots", category, StringComparison.OrdinalIgnoreCase))
                {
                    rentItems = _RentItems.AllRentItems.Where(i => i.Category.Name.Equals("Ботинки Лыжные")).OrderBy(i => i.Id);
                    currCategory = "Ботинки Лыжные";
                }
                else
                {
                    rentItems = _RentItems.AllRentItems.Where(i => i.Category.Name.Equals("Лыжи")).OrderBy(i => i.Id);
                    currCategory = "Лыжи";
                }
            }

            var rentObj = new RentItemViewModel
            {
                GetAllRentItems = rentItems,
                currentCategory = currCategory
            };

            ViewBag.Title = "На прокат";
            
            return View(rentObj);
        }
    }
}

NetCoreMvcClear/Views/Home/Index.cshtml
@model HomeViewModel

<h3>Прокат. Доступно.</h3>
<div class="row mt-5 mb-2">
    @{
        foreach (RentItem rentItem in Model.availableItems)
        {
            @Html.Partial("RentItemsTemplate", rentItem)
        }
    }
</div>

NetCoreMvcClear/Views/Order/Checkout.cshtml
@model Order

<div class="container">
    <h3>Оформление заказа</h3>
    <form asp-action="Checkout" method="post" class="form-horizontal">
        <div class="form-group">
            <label asp-for="Name"></label>
            <div class="col-12">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Surname"></label>
            <div class="col-12">
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Addr"></label>
            <div class="col-12">
                <input asp-for="Addr" class="form-control" />
                <span asp-validation-for="Addr" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Phone"></label>
            <div class="col-12">
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="EmailAddr"></label>
            <div class="col-12">
                <input asp-for="EmailAddr" class="form-control" />
                <span asp-validation-for="EmailAddr" class="text-danger"></span>
            </div>
        </div>
        <input class="btn btn-success" type="submit" value="Завершить заказ" />
    </form>
</div>

NetCoreMvcClear/Views/Order/Complete.cshtml
<h3>@ViewBag.Message</h3>

NetCoreMvcClear/Views/RentCart/Index.cshtml
@model RentCartViewModel

<div class="container">
    @foreach (var item in Model.rentCart.RentCartList)
    {
        <div class="alert alert-warning mt-3">
            <b>наименование:</b> @item.RentItem.Name <br />
            <b>Цена за единицу:</b> @item.RentItem.RentPrice.ToString("c") <br />
            <b>Количество:</b> @item.Quantity
        </div>
    }
    <hr />
    <a class="btn btn-danger" asp-controller="Order" asp-action="CheckOut">Оплатить</a>
</div>

NetCoreMvcClear/Views/RentItem/List.cshtml
<h3>Прокат.</h3>
<h4>@Model.currentCategory</h4>
<div class="row mt-5 mb-2">
    @{
        foreach (RentItem rentItem in Model.GetAllRentItems)
        {
            @Html.Partial("RentItemsTemplate",rentItem)
        }
    }
</div>

NetCoreMvcClear/Views/Shared/RentItemsTemplate.cshtml
@model RentItem

<div class="col-lg-4">
    <img class="img-thumbnail" src="@Model.ImgUrl" alt="@Model.Name" />
    <h4>Наименование: @Model.Name</h4>
    <p>Стоимость проката: @Model.RentPrice.ToString("c")</p>
    <p><a class="btn btn-warning" asp-controller="RentCart" asp-action="addToCart" asp-route-id="@Model.Id">Добавить в корзину</a></p>
</div>

NetCoreMvcClear/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/style.css" rel="stylesheet" type="text/css" />
</head>
<body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <a class="navbar-brand" href="/">Прорайдер</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" asp-controller="Home" asp-action="Index">Доступно выдать<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/RentItem/List">Вся база</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/RentItem/List/skyboots">Ботинки</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/RentItem/List/ski">Лыжи</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/RentCart">Корзина</a>
                </li>
            </ul>
            <form class="form-inline mt-2 mt-md-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>

    <div class="container mt-5">
        @RenderBody()
    </div>
    
    <footer class="container">
        <p class="float-right"><a href="#">Back to top</a></p>
        <p>© 2019 Все права защищены. · <a href="#">Соглашение</a></p>
    </footer>
    
    <script src="~/js/bootstrap.min.js"></script>
</body>
</html>